version: "3.8"

services:

  mariadb:
    env_file:
      - .env
    build: requirements/mariadb/.
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_pw
      - db_root_pw
    networks:
      - site-network
    restart: always

  wordpress:
    env_file:
      - .env
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - web:/var/www/html
    secrets:
      - wp_ad_pw
      - wp_usr_pw
      - db_pw
    networks:
      - site-network
    restart: always

  nginx:
    env_file:
      - .env
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - site-network
    restart: always

secrets:
  db_pw:
    file: secrets/db_pw
  db_root_pw:
    file: secrets/db_root_pw
  wp_ad_pw:
    file: secrets/wp_ad_pw
  wp_usr_pw:
    file: secrets/wp_usr_pw
  

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/timschmi/inception/src/db
      o: bind
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/timschmi/inception/src/web
      o: bind

networks:
  site-network:
    driver: bridge
