version: "3.8"

services:

  mariadb:
    # env_file: "./.env"
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - site-network
    restart: always

  wordpress:
    # env_file: "./.env"
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "9000:9000"
    volumes:
      - ./web:/var/www/html
    networks:
      - site-network
    restart: always

  nginx:
    # env_file: "./.env"
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - site-network
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/timschmi/Desktop/Inception/src/db
      o: bind

networks:
  site-network:
    driver: bridge
